/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeadersRouteImport } from './routes/_authenticated/leaders'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated/leaves'
import { Route as AuthenticatedPersonsRouteImport } from './routes/_authenticated/persons'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWeaponsRouteImport } from './routes/_authenticated/weapons'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedReportsViewRouteImport } from './routes/_authenticated/reports.view'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services.index'
import { Route as AuthenticatedServicesViewRouteImport } from './routes/_authenticated/services.view'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadersRoute = AuthenticatedLeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonsRoute = AuthenticatedPersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeaponsRoute = AuthenticatedWeaponsRouteImport.update({
  id: '/weapons',
  path: '/weapons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsViewRoute =
  AuthenticatedReportsViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedServicesRoute,
  } as any)
const AuthenticatedServicesViewRoute =
  AuthenticatedServicesViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => AuthenticatedServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaders': typeof AuthenticatedLeadersRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/persons': typeof AuthenticatedPersonsRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/services': typeof AuthenticatedServicesRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/weapons': typeof AuthenticatedWeaponsRoute
  '/reports/view': typeof AuthenticatedReportsViewRoute
  '/services/view': typeof AuthenticatedServicesViewRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaders': typeof AuthenticatedLeadersRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/persons': typeof AuthenticatedPersonsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/weapons': typeof AuthenticatedWeaponsRoute
  '/reports/view': typeof AuthenticatedReportsViewRoute
  '/services/view': typeof AuthenticatedServicesViewRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaders': typeof AuthenticatedLeadersRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/persons': typeof AuthenticatedPersonsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/services': typeof AuthenticatedServicesRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/weapons': typeof AuthenticatedWeaponsRoute
  '/_authenticated/reports/view': typeof AuthenticatedReportsViewRoute
  '/_authenticated/services/view': typeof AuthenticatedServicesViewRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/archive'
    | '/audit'
    | '/dashboard'
    | '/leaders'
    | '/leaves'
    | '/persons'
    | '/reports'
    | '/services'
    | '/users'
    | '/weapons'
    | '/reports/view'
    | '/services/view'
    | '/reports/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/archive'
    | '/audit'
    | '/dashboard'
    | '/leaders'
    | '/leaves'
    | '/persons'
    | '/users'
    | '/weapons'
    | '/reports/view'
    | '/services/view'
    | '/reports'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/archive'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaders'
    | '/_authenticated/leaves'
    | '/_authenticated/persons'
    | '/_authenticated/reports'
    | '/_authenticated/services'
    | '/_authenticated/users'
    | '/_authenticated/weapons'
    | '/_authenticated/reports/view'
    | '/_authenticated/services/view'
    | '/_authenticated/reports/'
    | '/_authenticated/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaders': {
      id: '/_authenticated/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof AuthenticatedLeadersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/persons': {
      id: '/_authenticated/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof AuthenticatedPersonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weapons': {
      id: '/_authenticated/weapons'
      path: '/weapons'
      fullPath: '/weapons'
      preLoaderRoute: typeof AuthenticatedWeaponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/view': {
      id: '/_authenticated/reports/view'
      path: '/view'
      fullPath: '/reports/view'
      preLoaderRoute: typeof AuthenticatedReportsViewRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedServicesRoute
    }
    '/_authenticated/services/view': {
      id: '/_authenticated/services/view'
      path: '/view'
      fullPath: '/services/view'
      preLoaderRoute: typeof AuthenticatedServicesViewRouteImport
      parentRoute: typeof AuthenticatedServicesRoute
    }
  }
}

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsViewRoute: typeof AuthenticatedReportsViewRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsViewRoute: AuthenticatedReportsViewRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedServicesRouteChildren {
  AuthenticatedServicesViewRoute: typeof AuthenticatedServicesViewRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
}

const AuthenticatedServicesRouteChildren: AuthenticatedServicesRouteChildren = {
  AuthenticatedServicesViewRoute: AuthenticatedServicesViewRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
}

const AuthenticatedServicesRouteWithChildren =
  AuthenticatedServicesRoute._addFileChildren(
    AuthenticatedServicesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadersRoute: typeof AuthenticatedLeadersRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedPersonsRoute: typeof AuthenticatedPersonsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWeaponsRoute: typeof AuthenticatedWeaponsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadersRoute: AuthenticatedLeadersRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedPersonsRoute: AuthenticatedPersonsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedServicesRoute: AuthenticatedServicesRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWeaponsRoute: AuthenticatedWeaponsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
